### ISSUE TITLE
TypeError: reduce() of empty iterable with no initial value

### ISSUE THREAD

**Issue by Wang001-hash** [lpryszcz/redundans#105]
$~/software/Genomics/redundans/redundans.py -v -i DNA_R1.fq.gz DNA_R2.fq.gz -l hifi.fa.gz -f ../p1.fasta -o p1_Redundans --threads 40 --noscaffolding --norearrangements --minimap2reduce

Options: Namespace(verbose=True, fastq=['DNA_R1.fq.gz', 'DNA_R2.fq.gz'], fasta='../p1.fasta', outdir='p1_Redundans', threads=40, resume=False, log=<_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, nocleaning=True, mem=2, tmp='/tmp', identity=0.51, overlap=0.8, minLength=200, minimap2reduce=True, index='4G', noreduction=True, joins=5, linkratio=0.7, limit=0.2, mapq=10, iters=2, noscaffolding=False, usebwa=False, longreads=['hifi.fa.gz'], populateScaffolds=False, minimap2scaffold=False, reference='', norearrangements=True, preset='asm5', nogapclosing=True, runmerqury=False, kmer=21)
Traceback (most recent call last):
  File "/home/wzt001/software/Genomics/redundans/redundans.py", line 727, in <module>
    main()
  File "/home/wzt001/software/Genomics/redundans/redundans.py", line 718, in main
    redundans(o.fastq, o.longreads, o.fasta, o.reference, o.outdir, o.mapq, \
  File "/home/wzt001/software/Genomics/redundans/redundans.py", line 323, in redundans
    fastas = [fasta, ]; _check_fasta(fasta)
  File "/home/wzt001/software/Genomics/redundans/redundans.py", line 284, in _check_fasta
    faidx = FastaIndex(open(lastOutFn))
  File "/home/wzt001/software/Genomics/redundans/bin/FastaIndex.py", line 80, in __init__
    self.totalcounts = reduce(lambda x, y: x+y, counts)
TypeError: reduce() of empty iterable with no initial value

**Comment by Dfupa** [comment]
Hi @ZhouTaoWang,

Based on the log and the command you used, I suspect the  error lies in the assembly  fasta file  you provided: `-f  ../p1.fasta
`. Without having a look at it, I can only speculate. Please check the assembly file is complete. Additionally, could you try submitting a job again providing a full path for it instead of '../' ?

Let me know how it went and if  I can be of further assistance.

**Comment by study591** [comment]
I have the same issue

**Comment by windliao2002** [comment]
The same issue as I run "redundans.py -v -f /home/liu/fq/1/G10.clean.all.contigs.fa -o /home/liu/fq/1/G10.clean.rh.contigs.fa --noscaffolding --nogapclosing --identity 0.7"

**Comment by Dfupa** [comment]
Hi all, 

Would you kindly provide me a toy dataset to reproduce this behavior and get to the bottom of it? with just some reads, one contig/scaffold it should be enough, something akin to the test datasets we provide through this repository.

**Comment by windliao2002** [comment]
> Hi all,
> 
> Would you kindly provide me a toy dataset to reproduce this behavior and get to the bottom of it? with just some reads, one contig/scaffold it should be enough, something akin to the test datasets we provide through this repository.

Excuse me, do u need "G10.clean.all.contigs.fa"?How can I send it?

**Comment by Dfupa** [comment]
Hi all, 

I just need (hopefully) a small subset of the dataset to try to reproduce your error. You can attach files to a github comment using the clip icon if they are not very big, Otherwise I would recommend just sharing it through google drive, nextcloud, dropbox, figshare or whatever you might prefer.

**Comment by Dfupa** [comment]
Hi all,

I am going to close this issue temporarily. If someone else faces the same issue or I receive a toy dataset to try and reproduce the behavior for further developing, I'll reopen it again.
