### ISSUE TITLE
questions regarding various steps in the pipeline

### ISSUE THREAD

**Issue by michieitel** [lpryszcz/redundans#13]
Hi!

I have some questions regarding some of the steps in the pipeline:

- redundancy removal:
How does the overlap detection work? I am wondering if it just based on LAST and if you specify e.g. 70% identity and 50% overlap than any contig that has 70% identity in any 50% part (start, end or middle) will be found. This way there is a good chance of wrong positive contigs to be marked redundant, especially when dealing with duplicated genes sitting on small contigs. When the duplicate has high similarity and spans 50% of the contig it might be wrongly marked as redundant and wrongly removed.

- gap closing:
I have roughly 150x coverage of PE reads and would like to use all of them for the gap closing, since I still have gaps after the scaffolding and based on the high coverage I assume that most gaps should be removed when using 100% instead of 20% of the short reads. How can I set this?

- pyScaf:

How is the scaffolding done with nanopore reads? How many reads are used by default to confirm a new linkage and can that be changed?

How does the algorithm deal with repeats and omits chimera artefacts. Usually, contigs break because of repeats that can't be unambiguously elongated.

I am asking because I have three independent assemblies (canu+pilon; Miniasm+pilon;Masurca). After the redundans pipeline, the per-base coverage (PE reads mapped to the assembly and histogram calculated in bedtools) indicates some merging even within the haploid contigs (see very right peak in the graph which drops after redundans for masurca and miniasm assemblies) [For the merging I used --identity 70 --overlap 80]

Sorry for bringing up all these issues at once (and for showing data of a polyploid genome). Any help/advice is highly appreciated.

Michael
[per_base_coverage_redundans_bedtool_genomecov_histo200_merging_4_raw_1kb-i70o80.pdf](https://github.com/Gabaldonlab/redundans/files/2301970/per_base_coverage_redundans_bedtool_genomecov_histo200_merging_4_raw_1kb-i70o80.pdf)

**Comment by lpryszcz** [comment]
Hi @michieitel , 

> redundancy removal

you're completely right, this can happen. note, by default redundans uses 0.5 identity and 0.8 overlap cut-off. it works well in our hand, but may no be optimal on certain scenarios. 

> gap closing:

use `--limit 1.0` parameter. by default 0.2 (20% of all reads are use). note, this will affect all steps, not only gap closing. what you could do, is take your final assembly from previous redundans run and just perform gap closing with `--limit 1.0. 

> pyScaf

this is still experimental. and it may indeed perform haploid contig merging as you experience.
