### ISSUE TITLE
Two redundans sites is confusing.

### ISSUE THREAD

**Issue by mathog** [lpryszcz/redundans#9]
I just discovered that (ironically) there are actually two redundans github sites:

https://github.com/Gabaldonlab/redundans

and

https://github.com/lpryszcz/redundans

Which one is used by the installer script http://bit.ly/redundans_installer ?

In any case, whichever it was, after the install the test did not run on my system.  That was posted as an issue on the other site.  Perhaps it should have been posted here?  Like I said, confusing

Thanks.

**Comment by lpryszcz** [comment]
I've been posting updates to both repos, but you're right. having two clones of the repo isn't reasonable. therefore I've merge them. 
thanks,
